apiVersion: missioncontrol.datastax.com/v1beta2
kind: MissionControlCluster
metadata:
  name: permanent-waves
  namespace: aaronsproj-5hc6uexb
spec:
  createIssuer: true
  dataApi:
    enabled: true
  encryption:
    internodeEncryption:
      certs:
        createCerts: false
      enabled: false
  k8ssandra:
    auth: true
    cassandra:
      config:
        cassandraYaml: {}
        dseYaml: {}
        jvmOptions:
          gc: G1GC
          heapSize: 2Gi
      datacenters:
        - config:
            cassandraYaml: {}
            dseYaml: {}
          datacenterName: entre-nous
          dseWorkloads: {}
          metadata:
            name: permanent-waves-entre-nous
            pods: {}
            services:
              additionalSeedService: {}
              allPodsService: {}
              dcService: {}
              nodePortService: {}
              seedService: {}
          networking: {}
          perNodeConfigMapRef: {}
          racks:
            - name: r30
              nodeAffinityLabels: {}
          size: 3
      resources:
        requests:
          cpu: 1000m
          memory: 4Gi
      serverImage: datastax/hcd:1.0.0-rc.1
      serverType: hcd
      serverVersion: 1.0.0
      storageConfig:
        cassandraDataVolumeClaimSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: gp3
      superuserSecretRef:
        name: permanent-waves-superuser
